FROM cmwn/front-node:6-wheezy

MAINTAINER Chuck "MANCHUCK" Reeves <chuck@manchuck.com>

#RUN apt-get update && apt-get install -y --no-install-recommends \
#    && wget http://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz \
#    && tar -xzvf ruby-2.3.1.tar.gz \
#    && cd ruby-2.3.1/ \
#    && ./configure \
#    && make \
#    && make install \
#    && ruby -v \
#    && npm install -gq gulp eslint eslint-plugin-react babel-eslint webdriverio wdio-mocha-framework babel-core

WORKDIR /var/www
